### ISSUE TITLE
Offline installer deletes it self after installing?!

### ISSUE THREAD

**Issue by SychoAN** [VHSgunzo/lux-wine#19]
plz fix this
after download 1.6gb lwrun file 
it installed successfully 
but then it removed the installer...I wanted offline installer so I can keep it !

**Comment by VHSgunzo** [comment]
lwrun is not deleted, but simply moved to the directory from where it
should be launched in the future.
To make it easier for you to install, I recommend simply copying lwrun in
advance from your external disk or from somewhere else to the target system
and running it there for installation.

The path where lwrun installs: ~/.local/share/LuxWine/bin/lwrun

You can also put lwrun on a RO medium or, for example, an iso image, then
it will be copied when installed on the target system.

сб, 23 сент. 2023 г. в 17:12, SychoAN ***@***.***>:

**Comment by SychoAN** [comment]
> @SychoAN lwrun is not deleted, but simply moved to its working directory. To make it easier for you to install, I recommend simply copying lwrun in advance from your external disk or from somewhere else to the target system and running it there for installation. The path where lwrun installs: ~/.local/share/LuxWine/bin/lwrun You can also put lwrun on a RO medium or, for example, an iso image, then it will be copied when installed on the target system.

Thanks for your hard work on this project
this helped me a lot as a beginner to use wine and proton
