### ISSUE TITLE
About of: Configuration files for different EXEs

### ISSUE THREAD

**Issue by Milor123** [VHSgunzo/lux-wine#20]
Hi bro, i want ask about of the feature **"Ability to create separate configuration files for different EXEs"** 

how can i configure it? when I press in lux apps settings this shows it:
![image](https://github.com/VHSgunzo/lux-wine/assets/14153649/9c36742d-cad6-4579-9930-4b0150f3a998)

What should i do?
do you have a manual or wiki for know this things?
Thank u very much for your project !!

**Comment by VHSgunzo** [comment]
@Milor123 
Hi, to create a separate config for the exe: 
Open its directory in the file manager -> right-click on exe -> select "Open with" -> "Settings" with the Lux Wine icon

You can also quickly open the settings from the Application Menu -> Wine Apps -> right click on the application -> Settings, if the application menu in your DE supports this

After saving the settings, a file with the same name as the exe and with the extension .wcfg will be created in the same directory. Also for quick access it can be opened from GUI Lux Wine -> Apps settings

**Comment by Milor123** [comment]
> @Milor123 Hi, to create a separate config for the exe: Open its directory in the file manager -> right-click on exe -> select "Open with" -> "Settings" with the Lux Wine icon
> 
> You can also quickly open the settings from the Application Menu -> Wine Apps -> right click on the application -> Settings, if the application menu in your DE supports this
> 
> After saving the settings, a file with the same name as the exe and with the extension .wcfg will be created in the same directory. Also for quick access it can be opened from GUI Lux Wine -> Apps settings

Ohh perfects, is great !! Thank u very much bro. I Love you app!
