### ISSUE TITLE
How to stop all the notifications 

### ISSUE THREAD

**Issue by SychoAN** [VHSgunzo/lux-wine#21]
when  I launch any exe I get .... Checking for updates... Game mode ON
can you tell me how to disable this notifications ?
or at least give me the name of this app to block from my notification manager
![image](https://github.com/VHSgunzo/lux-wine/assets/61439740/c740021a-3938-46fe-8889-b1316c99028d)

**Comment by VHSgunzo** [comment]
@SychoAN 
For disable "Game mode ON/OFF" disable `GameMode` in LW settings:
![image](https://github.com/VHSgunzo/lux-wine/assets/57139938/c26177ed-4fa3-42e7-968b-b633f7eb4552)



"Checking for updates... "
Does this also happen every time you run the EXE?

**Comment by SychoAN** [comment]
> @SychoAN For disable "Game mode ON/OFF" disable `GameMode` in LW settings: ![image](https://private-user-images.githubusercontent.com/57139938/290869884-c26177ed-4fa3-42e7-968b-b633f7eb4552.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTY2MDcsIm5iZiI6MTcwMjY1NjMwNywicGF0aCI6Ii81NzEzOTkzOC8yOTA4Njk4ODQtYzI2MTc3ZWQtNGZhMy00MmU3LTk2OGItYjYzM2Y3ZWI0NTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2MDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NTBlMTRhN2I4NTdjNmZjMmZhYjRkNTdiODQ4NDZlYjAwNGQ4MWFmNThmMzY3MTc1NzFjMDFmM2FkNzJmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vGrRYRwQ-_uH8Y4RFt6Ro2qbgMvob4hCwV9bMtSatrM)
> 
> "Checking for updates... " Does this also happen every time you run the EXE?

But I don't wanna disable gamemode...Just the notification

and checking for updates happens every day and I get like 3 notifications beside game mode

**Comment by VHSgunzo** [comment]
@SychoAN 
That particular update check cannot take place every day, because it is configured to check every three days. if you did not change the verification parameters yourself in `~/LuxWine/bin/lwrap`

Anyway, here's what you can do:

Disable notify for LW container (~/LuxWine/bin/lwrun):
```
echo DONT_NOTIFY=1 >> ~/LuxWine/bin/Run.rcfg
```

Disable notify for LW (~/LuxWine/bin/lux-wine):
```
echo 'NO_NOTIFY=1' >> ~/LuxWine/bin/Run.rcfg
```

Disable gamemode config in LW container (It prescribes sending notifications about its start and stop):
```
echo 'BUWRAP_ARGS+=(--bind /dev/null /etc/gamemode.ini)' >> ~/LuxWine/bin/Run.rcfg
```

**Comment by SychoAN** [comment]
Didn't work still sends Gamemode ON...maybe I should logout and login

**Comment by VHSgunzo** [comment]
> Didn't work still sends Gamemode ON...maybe I should logout and login

You just need to restart everything related to LW

**Comment by VHSgunzo** [comment]
@SychoAN 
Also check that there are no lines related to sending notifications in your gamemode config in the user's home directory
